/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_starquest_usermanagement_SaltGenerator */

#ifndef _Included_com_starquest_usermanagement_SaltGenerator
#define _Included_com_starquest_usermanagement_SaltGenerator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_starquest_usermanagement_SaltGenerator
 * Method:    getSalt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_starquest_usermanagement_SaltGenerator_getSalt
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
