kie:
  registrationKIESession: "bpm.starquest.registrationKSession"
  registrationBPMProcessflowName: "SQRESTfulPost"
  registrationBPMProcessflowFulllName: "com.starquest.kie.process.userreg.SQRegiostrationProcess1"
  registrationPasswordRulesKSession: "rules.starquest.registrationPasswordKSession"
  registrationBPMWorkflow: "registrationBPMWorkflow"
  registrationPasswordRulesflow: "registrationPasswordRulesflow"
  registrationPasswordRulesFailflow: "registrationPasswordRulesFailflow"
  registrationPasswordRulesSuccessflow: "registrationPasswordRulesSuccessflow"
  registrationPersistBPMWorkflow: "registrationPersistBPMWorkflow"
  globalMediaTypeJson: "APPLICATION_JSON"
  globalOperationPost: "POST"
  WIApplyRegistrationRules: "WIApplyRegistrationRules"
  WIProcessFailedRegistration: "WIProcessFailedRegistration"
  WIEncryptKeyFields: "WIEncryptKeyFields"
  registrationRulesFailed: "registrationRulesFailed"
  registrationRulesSuccess: "registrationRulesSuccess"
  registrationEncryptionFailed: "registrationEncryptionFailed"
  registrationEncryptionSuccess: "registrationEncryptionSuccess"
  registrationPersistenceFailed: "registrationPersistenceFailed"
  registrationPersistenceSuccess: "registrationPersistenceSuccess"
  registrationProcessFlowEnd: "registrationProcessFlowEnd" 
  
  
  
  endPoints:
    - 
      endPoint: "registrationBPMWorkflow" 
      url: "http://localhost:8282/sq/registrationkie/startRegistrationKieProcess"
      context: "/sq/registrationkie/startRegistrationKieProcess"
      mediaType: "APPLICATION_JSON"
      operation: "POST"
    - 
      endPoint: "registrationPasswordRulesflow" 
      url: "http://localhost:8282/sq/registrationkie/applyPasswordRules"
      context: "/sq/registrationkie/applyPasswordRules"
      mediaType: "APPLICATION_JSON"
      operation: "POST"
    - 
      endPoint: "registrationPasswordRulesFailflow" 
      url: "http://localhost:8282/sq/registrationkie/processPasswordRulesFail"
      context: "/sq/registrationkie/processPasswordRulesFail"
      mediaType: "APPLICATION_JSON"
      operation: "POST"  
    - 
      endPoint: "registrationPasswordRulesSuccessflow"
      url: "http://localhost:9292/sq/encryption/newVer"
      context: "sq/encryption/"
      mediaType: "APPLICATION_JSON"
      operation: "POST"
    -
      endPoint: "registrationPersistBPMWorkflow"
      url: "http://localhost:7272/sq/saveSQUser"
      context: "sq/saveSQUser/"
      mediaType: "APPLICATION_JSON"
      operation: "POST"