kie:
  registrationKIESession: "bpm.starquest.registrationKSession"
  registrationBPMProcessflowName: "SQRESTfulPost"
  registrationBPMProcessflowFulllName: "com.starquest.kie.process.userreg.SQNewRegistrationProcess"
  registrationPasswordRulesKSession: "rules.starquest.registrationPasswordKSession"
  registrationBPMWorkflow: "registrationBPMWorkflow"
  registrationPasswordRulesflow: "registrationPasswordRulesflow"
  registrationPasswordRulesFailflow: "registrationPasswordRulesFailflow"
  registrationPasswordRulesSuccessflow: "registrationPasswordRulesSuccessflow"
  globalMediaTypeJson: "APPLICATION_JSON"
  globalOperationPost: "POST"
  WIApplyRegistrationRules: "WIApplyRegistrationRules"
  WIProcessFailedRegistration: "WIProcessFailedRegistration"
  WIEncryptKeyFields: "WIEncryptKeyFields"
  endPoints:
    - 
      endPoint: "registrationBPMWorkflow" 
      url: "http://localhost:8282/sq/registrationkie/startRegistrationKieProcess"
      context: "/sq/registrationkie/startRegistrationKieProcess"
      mediaType: "APPLICATION_JSON"
      operation: "POST"
    - 
      endPoint: "registrationPasswordRulesflow" 
      url: "http://localhost:8282/sq/registrationkie/applyPasswordRules"
      context: "/sq/registrationkie/applyPasswordRules"
      mediaType: "APPLICATION_JSON"
      operation: "POST"
    - 
      endPoint: "registrationPasswordRulesFailflow" 
      url: "http://localhost:8282/sq/registrationkie/processPasswordRulesFail"
      context: "/sq/registrationkie/processPasswordRulesFail"
      mediaType: "APPLICATION_JSON"
      operation: "POST"  
    - 
      endPoint: "registrationPasswordRulesSuccessflow" 
      url: "http://localhost:8282/sq/registrationkie/registrationPasswordRulesSuccessflow"
      context: "/sq/registrationkie/registrationPasswordRulesSuccessflow"
      mediaType: "APPLICATION_JSON"
      operation: "POST"